 version: "3.9"

services:
  app:
    build: .
    container_name: synclynk-app
    ports:
      - "8080:80"
    env_file: .env
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: synclynk-mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: "${DB_USERNAME}"
      MONGO_INITDB_ROOT_PASSWORD: "${DB_PASSWORD}"
    volumes:
      - mongo_data:/data/db
    # Optional: Port herausreichen, falls du Robo3T o. Ä. nutzen willst
    # ports:
    #   - "27017:27017"

volumes:
  mongo_data:
